spring:
  application:
    name: stock-tracker
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:stdb
    username: sa
    password: pw
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /st
